### ISSUE TITLE
Google redirects in many links on SPDX 2.1 specification HTML version

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/spdx-spec#1]
Hi Kate, Gary recommended I open this bug here. Please let me know if this would be better handled elsewhere. Here's the issue:

----

I noticed a minor issue in the HTML version of SPDX 2.1 specification. All of the HTML links in that section go through the Google redirect service, prepending the SPDX URL with a Google URL (e.g. https://www.google.com/url?q=http://spdx.org/spdx-license-list/matching-guidelines&sa=D&ust=1473291615549000&usg=AFQjCNGAF8fFt6wIxj4Sj1XSOS0LdR2a5A). I'm guessing that this may be due to copy-and-paste from a gdoc draft?

For the PDF version, I didn't do a thorough check, but did look at Appendix II, and this issue does not seem to affect that version. However, I did notice some links to Google Docs in Appendix IV there (the 2nd and 3rd links, to "Appendix I.1" and "Appendix I.2") which are probably meant to be internal links rather than to an s.sfusd.edu Google Doc (this was present in both the PDF and HTML version of the spec).

----
Best,
Brad

**Comment by tsteenbe** [comment]
Google redirecting links should be resolved after we switch to new MarkDown-built specification currently committed to this repository. You can browse the current development version at https://spdx.github.io/spdx-spec/

**Comment by goneall** [comment]
Since this is closed in the source for 2.1.1 and will be resolved as soon as it is released, I'm closing this issue.  If it is still a problem after 2.1.1 is release, this can be re-opened

**Comment by pombredanne** [comment]
All links in the spec still redirect through Google, which is IMHO both bad, useless and extremely impolite behaviour.

**Comment by seabass-labrax** [comment]
@pombredanne, I agree, it's always better to have clean hyperlinks. However, I'm looking through https://spdx.github.io/spdx-spec/ and I can't find any such redirects.

Has this already been fixed? If not, please would you point me to a few examples of these redirects so that I can go about fixing some of them? Thanks!

**Comment by seabass-labrax** [comment]
@pombredanne, I've done some further investigation into this; please tell me if this is consistent with what you've identified or if I'm missing something here :)

I did find redirect links on the [HTML page for version 2.1 of the specification](https://spdx.dev/spdx-specification-21-web-version/). Although not *all* the links on this page are redirects, there are 449 by my count.

However, I couldn't find any redirect links in the tips of any branches of this repository. I imagine this means either that the redirects are an artefact of copying the HTML to the https://spdx.dev/ WordPress site, or that the redirect links were present and then fixed in this repository but the website was not updated to include these changes.

The only other HTML specification ([v2.2](https://spdx.github.io/spdx-spec/)) doesn't have any redirects, which I presume is because it is generated directly from the GitHub repository by MkDocs.

If the problematic URLs are indeed present only on the WordPress site and not in this repository, how about we bring this up on one of the mailing lists, @pombredanne?

**Comment by kestewart** [comment]
Closing this as I believe it's been sorted now.   But please reopen if you spot a location of a problem.
