### ISSUE TITLE
move Matching Guidelines to appendix in spec

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-spec#134]
Currently the SPDX License List matching guidelines are housed on a web page on the website. The legal team has discussed moving them to the new (still working on) DOCS section of the license list github repo, but I'm wondering that given we already have Appendix II that talks about the matching guidelines, why not include all the relevant info there and have the guidelines there too?
https://github.com/spdx/spdx-spec/blob/master/chapters/appendix-II-license-matching-guidelines-and-templates.md

Also noting that Appendix II is woefully out of date... will add to to-do list to work on that!

**Comment by swinslow** [comment]
Makes sense to me! As long as the HTML version of the spec will be set up so that we can link directly to the Appendix, so that we can refer people to it directly.

(And I think that is the case, for the new spec generator that has been a GSoC project this summer.)

**Comment by kestewart** [comment]
Any progress on updating the matching guidelines?    +1 on getting an update in the existing appendix now that GSoC is over.

**Comment by swinslow** [comment]
@kestewart I'm on it  :)

**Comment by swinslow** [comment]
The matching guidelines have now been added into Appendix II in the development/v2.2 branch: see https://github.com/spdx/spdx-spec/blob/development/v2.2/chapters/appendix-II-license-matching-guidelines-and-templates.md

(note that the PR at #139 wasn't itself merged, but this was added in commit 7f700ff)

There was a comment from @iamwillbar in the discussion of the earlier PR (see https://github.com/spdx/spdx-spec/pull/139#issuecomment-546056071) suggesting that this might be pulled back out of an appendix for v3.0, and located somewhere else in the repo (I assume spdx-spec rather than license-list-XML). If so, that can be addressed as part of the broader v3.0 refactor.

In the meantime, though, I think this issue can now be closed as resolved, unless any of @kestewart @jlovejoy @iamwillbar feel differently  :)

**Comment by iamwillbar** [comment]
Since #139 has been merged I'm going to close this issue.
