### ISSUE TITLE
Add additional HASH Algorithms to SPDX Vocabulary

### ISSUE THREAD

**Issue by init-dcat-ap-de** [spdx/spdx-spec#144]
[https://github.com/SEMICeu/DCAT-AP](https://github.com/SEMICeu/DCAT-AP), and therefore [https://github.com/GovDataOfficial/DCAT-AP.de](https://github.com/GovDataOfficial/DCAT-AP.de) uses spdx:Checksum.

Unfortunately, SPDX currently only supports 3 algorithms, while we need more. At the moment, we use our own list ([https://www.dcat-ap.de/def/hashAlgorithms/](https://www.dcat-ap.de/def/hashAlgorithms/)) for the German application profile, but we would prefer an official approach.

The following algorithms are in use by data providers but missing at spdx:
MD-1, MD-2, SHA-224, SHA-384, SHA-512.

Our request is to add them to the list of accepted values for [algorithm](http://spdx.org/rdf/terms#algorithm).

See also: [https://github.com/SEMICeu/DCAT-AP/issues/44](https://github.com/SEMICeu/DCAT-AP/issues/44)

**Comment by goneall** [comment]
I see no problem adding this in the 2.2 version of the spec. with the possible exception of MD-1.

@init-dcat-ap-de Can you provide a reference for the MD-1 hash algorithm?  It doesn't look like that algorithm was published.

**Comment by init-dcat-ap-de** [comment]
I can't. It seems like this is an error on our side.
I'll look into it, but it probably doens't exist :)

**Comment by kestewart** [comment]
Pull request welcome.

**Comment by swinslow** [comment]
I don't see a problem with adding these as permitted *optional* algorithms for hashes.

One comment though -- I believe we will still need to keep SHA1 as a *mandatory* hash for Files, unless the Package Verification Code algorithm is changed.

Per a related comment I just added at https://github.com/spdx/spdx-spec/issues/106#issuecomment-562698471, the Package Verification Code algorithm is derived from knowing the SHA1 values for all of the Files in that Package. If SHA1 values became optional rather than mandatory, then you wouldn't be able to validate a Package Verification Code with just the document in hand.

It might be that the solution to this is to modify the Package Verification Code algorithm... or just to keep SHA1 as mandatory for now. Either way, just flagging this as a consideration to be considered  :)

**Comment by kestewart** [comment]
Suggest we leave SHA1 as the mandatory one for now, but I see only benefit in adding additional checksums.    Based on above discussion - are all ok with adding: 
Message Digest Algorithms: [MD2](https://tools.ietf.org/html/rfc1319),  [MD4](https://tools.ietf.org/html/rfc1320),  [MD6](https://groups.csail.mit.edu/cis/md6/)
As well as the [Secure Hash Algorigthms](https://en.wikipedia.org/wiki/Secure_Hash_Algorithms):   SHA-224, SHA-384, SHA-512  ?

**Comment by goneall** [comment]
> One comment though -- I believe we will still need to keep SHA1 as a mandatory hash for Files, unless the Package Verification Code algorithm is changed.

I agree
