### ISSUE TITLE
How to create SPDX relationship for package that occurs multiple with different subtrees

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#453]
In OSS Review Toolkit we are implementing SPDX 2.2 including rendering out a package's dependency tree as a set of SPDX relationship but we would like to know how to correct encode packages that occurs multiple in subtrees with different dependencies. 

See example below, in SPDX relationship model it not possible to express Package B 1.0 having two different subtrees. This use case occurs in npm (yarn Workspaces).

```
Package A 1.0 
- hasChild: Package B 1.0
   - hasChild: Package C 1.0
- hasChild: Package D 1.0
  - hasChild: Package B 1.0
      - hasChild: Package C 1.1
```

**Comment by goneall** [comment]
Hopefully this isn't too common of a situation, but I can see how this can occur.

I can think of 2 possible solutions:

1. Treat the 2 `Package B 1.0` with the different dependencies as two different packages or package versions
2. Flatten the dependencies where `Package A 1.0` includes a de-duplicated list of all children at the top level

The logic for #1 is `Package B 1.0` is actually 2 different packages since they have different dependencies even though they have the same name and same version number.  The SPDX ID's would be different and the relationships would be different, but the names and versions would be the same.  This approach would make sense if the dependency information was stored with `Package B 1.0` yet the 2 copies had different metadata.

Solution #2 would make sense if the package dependency data was stored in a metadata build file with `Package A 1.0` and the metadata stored with `Package B 1.0` is identical.

I'm quite curious about other views on this rather interesting issue.

**Comment by swinslow** [comment]
I tend to agree with @goneall's solution number 1. If two different instances of the package have different dependency trees, it seems to make sense to treat them as different packages by giving them different SPDX IDs within the document.

**Comment by goneall** [comment]
Reference the newly moved https://github.com/spdx/spdx-examples

@tsteenbe if this resolves this issue, please close

**Comment by kestewart** [comment]
@tsteenbe - has this been resolved with the examples?

**Comment by kestewart** [comment]
Closing this now.   Please reopen if you disagree.
