### ISSUE TITLE
license expressions grammar

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-spec#456]
This is about **Annex D**, where we define the license expressions.

The ABNF grammar does not look correct to me...

In both definitions of `compound-expression` and `license-expression` we can delete the superfluous initial `1*1`, which says "minimum 1, maximum 1", which of course is the same as omitting it ("exactly 1").

Then, the definition of `license-expression` includes both `simple-expression` and `compound-expression`, but `compound-expression` can already be a single `simple-expression`, so there is no need to have them both.

**Comment by Cynical-Optimist** [comment]
#### "`1*1` is superfluous"
I agree completely. +1

#### "`compound-expression` makes `simple-expression` superfluous"
Not quite. Look at the `"WITH"` line.
`compound-expression "WITH" license-exception-id` isn't (in general) a valid license expression. It specifically has to be a `simple-expression`. That's why they're not interchangeable.

**Comment by Cynical-Optimist** [comment]
Two more issues:

* Redundant `1*`
The definition of `license-ref` involves `1*(idstring)`, but the definition of `idstring` already used a `1*`. so the second `1*` is redundant.

* Markdown removes spaces at the start lines
There are three lines that start with 2 spaces. According to the definition of ABNF, these spaces are an important part of the definition. They show that these lines are a continuation of the line above.

The spaces are present in the raw markdown file, and they're correct (they ought to be there), but they dissappear when the document is actually rendered (because markdown ignores them).

The whole definition should probably be quoted with triple backticks, and treated like a code snippet, so that markdown won't change the text.

This would also mean we could remove the backslash in the license-ref definition. (Which I assume is there just to escape the asterisk).

**Comment by goneall** [comment]
It looks like this was partially resolved in 2.3, but we still have the redundant expressions.

Since we're past the review period for 2.3, I'm pushing this to a 3.0 fix.

**Comment by zvr** [comment]
Closing this, as the grammar of 3.0 has the fixes already integrated.
