### ISSUE TITLE
Not an Issue: Request to loosen constraints for SPDXID

### ISSUE THREAD

**Issue by rjb4standards** [spdx/spdx-spec#499]
I'm trying to use a filename to construct an SPDXID: SPDXRef-SAGPM_Vendor_Data.csv, but the under bars are causing a problem. Any chance the SPDXID constraint for [idstring] may become more lenient and allow any printable UTF-8 character in the, i.e. SPDXRef-UTF-8idstring?

4.2.4 Data Format: "SPDXRef-"[idstring]

**where [idstring] is a unique string containing letters, numbers, . and/or -.**

Invalid ID for SPDX Element: SPDXRef-SAGPM_Vendor_Data.csv. Must be either a valid SPDX ID or Anonomous. in SAGPM_Vendor_Data.csv in SAGPM_Vendor_Data.csv in SAG-PM

Thanks for your consideration.

**Comment by rjb4standards** [comment]
Gary, the real problem is I don't control what a vendor may put in their Filename: value. Today its _ tomorrow it's + or something else, like #. I certainly understand your concerns with RDF impact but I suspect this may trip up many vendors looking to use automated tools to create an SPDX SBOM in TV format, using the files contained in source tree. I'm thinking the simplest way around this for me may be to use Anonymous, but that losses fidelity with the source. Would it be possible to adapt the RDF implementation to use XML's escape mechanism for flagrant characters? Thx.

**Comment by goneall** [comment]
> the real problem is I don't control what a vendor may put in their Filename

OK - I understand the issue now.

> Would it be possible to adapt the RDF implementation to use XML's escape mechanism for flagrant characters?

Yes - however, there are other serialization formats that would be impacted.  This would probably be a rather impactful change.

Since we have a file name property for the files, I would suggest not trying to use the file name directly for the SPDX ID.  You could escape the special characters when converting the file name to the ID (e.g. converting all disallowed ID characters to two underscores or some other unlikely character grouping).

I can think of one other possible issue with using files names - the SPDX ID's must be unique within the file.  Since more than one package can be included in an SPDX document, having multiple files with the same name will be common.

**Comment by rjb4standards** [comment]
Thanks, Gary. Your point about multiple files with the same name is one of the mines that I tripped over: https://support.microsoft.com/en-us/topic/january-12-2021-kb4598242-os-builds-19041-746-and-19042-746-ab18a1a1-d572-598f-4d86-7137aad34056 look at the files list Aaaarrggg: https://download.microsoft.com/download/1/e/a/1eaed84f-3e0d-4938-86e1-42cd0aa7f9c8/4598242.csv 

I'm thinking Anonymous may be the path of least resistance for SPDXID's

**Comment by swinslow** [comment]
Hi @rjb4standards, sharing a couple of thoughts here in case it's useful:

For [Zephyr's implementation of creating SPDX documents](https://github.com/zephyrproject-rtos/zephyr/pull/34555) in their build process, I ran into this same issue. Instead of using just integers for File IDs (e.g. `SPDXRef-1`, `SPDXRef-2`, etc.) I wanted to give them IDs that were meaningful. However, as @goneall noted, the IDs need to (1) appropriately handle any special characters, and (2) ensure uniqueness within the scope of that SPDX document.

I ended up handling this using the process [here](https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/west_commands/zspdx/spdxids.py), which is basically the following process when walking through all files in a directory / subdirectories:
1. Strip out the path and use just the filename
2. Convert any non-SPDX-ID-safe characters to a hyphen
3. Keep a running tally of how many times I've seen this particular converted name
4. If I've already seen it previously, start adding a trailing integer (`-1`, `-2`, ...) for each subsequent one
5. There's a bit of an edge case where the original filename itself might end in `-1`, so this also handles that case to ensure uniqueness

I don't know if this is helpful, but figured I'd share just in case!

**Comment by rjb4standards** [comment]
Thanks, Steve. Much appreciate the suggestion. Looks like I need to define a new function getSPDXID(filename).
Thanks for sharing your insights.
Dick Brooks

**Comment by goneall** [comment]
Moving this issue to 3.0 since it may have compatibility implications

**Comment by goneall** [comment]
@rjb4standards - is this resolved in the 3.0 spec?

**Comment by goneall** [comment]
I don't think this is applicable for 3.0 any more, @rjb4standards - if you disagree, please reopen

**Comment by rjb4standards** [comment]
I agree Gary. Thanks for closing.

 

Thanks,

 

Dick Brooks

  

Active Member of the CISA Critical Manufacturing Sector, 

Sector Coordinating Council – A Public-Private Partnership

 

 <https://reliableenergyanalytics.com/products> Never trust software, always verify and report! ™

 <http://www.reliableenergyanalytics.com/> http://www.reliableenergyanalytics.com

Email:  ***@***.***> ***@***.***

Tel: +1 978-696-1788
