### ISSUE TITLE
Remove packages.annotations from JSON schema

### ISSUE THREAD

**Issue by SamuraiAku** [spdx/spdx-spec#536]
There is no annotations field inside a package (see Section 3 of the spec). This is also duplicative of the annotations module at the top-level, which is described in Section 8 of the spec.

**Comment by goneall** [comment]
There is an inconsistency between the UML model, RDF serialization format and the tag/value serialization for annotations.

In the [model and RDF serializations](https://spdx.github.io/spdx-spec/appendix-III-RDF-data-model-implementation-and-identifier-syntax/), annotations are a property Element.  In tag/value the are a list at the document level.

This issue is already discussed in issue #517 (currently open) - I'm going to close this out as a duplicate.  We should continue the discussion in issue #517
