### ISSUE TITLE
Support multiple SPDX file format like project HayStack 

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#55]
[Project Haystack](https://project-haystack.org/doc/Intro#data) supports multiple formats

• Formats: JSON, Zinc (typed CSV), Trio (YAML)
• RDF/linked data (Microdata, RDFa, JSON-LD, Turtle, SPARQL)

Idea - could we use similar concept to add support for multiple formats in SPDX?

**Comment by goneall** [comment]
Working on a prototype which will support YAML and JSON.

One issue I'm working through is how to flatten the graph of relationships.  If I do a pure JSON or YAML serialization of the objects, I get an infinite loop with bi-directional relationships (the graph of relationships is not restricted to a directed graph for SPDX).

I have a few ideas on how to resolve, some involve minor changes to the spec, other approaches do not.  I'll do a bit more investigation and prototyping before making any proposals.

**Comment by pombredanne** [comment]
Having a DAG is the sane way to go. RDF is nuts there IMHO.

**Comment by goneall** [comment]
> Having a DAG is the sane way to go.

We debated this during the development of SPDX 2.0 at the SPDX leadership conference and concluded on allowing cycles.  Wasn't my favorite approach due to the complications in the tools, but it was the conclusion of the group and is now implemented.

> RDF is nuts there IMHO.

Just a note - the use of graphs with cycles is completely independent of whether we support RDF.  The nice thing is we don't require the use of RDF to use SPDX, you're welcome to use the tag/value format.

**Comment by goneall** [comment]
I prototyped a YAML translator for the SPDX tools.  The source is located in the [yamlsupport](https://github.com/spdx/tools/tree/yamlsupport) branch.

Attached is the YAML format for the example SPDX document.  Note that the example includes a few fields which are deprecated (e.g. reviewer, file dependencies).
[SPDXRdfExample-v2.1.yaml.txt](https://github.com/spdx/spdx-spec/files/1584613/SPDXRdfExample-v2.1.yaml.txt)

**Comment by goneall** [comment]
In the prototype above, I wrapped all of the SPDX elements (files, packages, snippets) in the type name using a simple type (e.g. package, snippet, file).

This greatly simplifies the serialization and deserialization of the YAML files.  It also closely matches the terms used in the RDF spec.

An alternative would be to not wrap the elements and pre-pend the property names with the name of the type (e.g. packageName, fileName, fileChecksum).

The alternative would closer match the tag/value spec but would complicate the tooling for any object oriented programming model.  I also personally think the wrapped approach is more readable since in many text editors the wrapping highlights all the related fields.

These two approaches is something we should discuss on one of the upcoming technical calls.

**Comment by kestewart** [comment]
From discussion on tech call today,  adhering to the model for JSON and YAML is fine.   We need to pull into discussion users of tagvalue to decide if there are changes needed there,  or the naming will persist as is.

**Comment by kestewart** [comment]
From meeting today,   as long as we agree on set of rules for supporting new format.
- tooling - library interchange support
- testing - identify community willing to support for testing of specific format.
- specification - asker helps document new format information.

There is general agreement on usefulness of Multiple formats under the above set of rules for 2.2.
Naming convention aligned with RDFa will be used in translated formats.   JSON & YAML likely candidates based on prototype.

We will separate discussion of deprecating specific file formats to 3.0 creation timeframe.

**Comment by jeremiah** [comment]
@kestewart @goneall Thanks for this work Gary and Kate. I would like to offer to help test the YAML / JSON formats. I'm willing to help set the testing scope too, in particular I'd like to avoid testing specific tools rather whether the formats adhere to specification and are valid JSON, YAML, etc. Personally I see the value in have a something run on the file system, generate the SPDX JSON / YAML, then render that resulting file in a tool like Angular to create human readable HTML, thus avoiding lock-in to various tooling or programming language's preferred data format.

**Comment by goneall** [comment]
@jeremiah Thanks for volunteering the help!  

I'll be working on a translator tool in the github.spdx/tools repo.  Currently, I use an example SPDX file for the unit tests.  One thought is to create a more complete document to test the formats.  I could then use that to test the translation tools as well.

> Personally I see the value in have a something run on the file system, generate the SPDX JSON / YAML

This sounds like a tool as well ;)  If this is a tool, we could add it to the SPDX github repository under an Apache license to make it accessible to the community.

As I am thinking about testing the actual spec, I'm wondering how we want to document YAML and JSON in the spec.

@kestewart Do we want to add add a description and examples for every field?  This approach would be similar to how we handle documenting both RDF and tag/value.  A more radical approach is to have the specification be more like a vocabulary spec and have appendices document the format specific implementations.  Another option is to move to documenting only the JSON fields (since that seems to be the currently most popular format) and moving the other formats to an appendix.

**Comment by goneall** [comment]
The [Yamlsupport](https://github.com/spdx/tools/tree/yamlsupport) branch of the SPDX tool has been updated to output JSON and XML formats.  I could not get the XML format to pretty print, so it is a bit ugly, but the structure is there.

I'm attaching the SPDX example file in tag/value (.spdx.txt), JSON (.json.txt), YAML (.yaml.txt) and XML (.xml.txt
[SPDXRdfExample-v2.1.json.txt](https://github.com/spdx/spdx-spec/files/2288883/SPDXRdfExample-v2.1.json.txt)
[SPDXRdfExample-v2.1.xml.txt](https://github.com/spdx/spdx-spec/files/2288884/SPDXRdfExample-v2.1.xml.txt)
[SPDXRdfExample-v2.1.yaml.txt](https://github.com/spdx/spdx-spec/files/2288885/SPDXRdfExample-v2.1.yaml.txt)
[SPDXTagExample-v2.1.spdx.txt](https://github.com/spdx/spdx-spec/files/2288886/SPDXTagExample-v2.1.spdx.txt)



) formats for review.

**Comment by goneall** [comment]
Discussed this on the tech call on 23 April 2019:

- @swinslow was getting some feedback that JSON format would help the SPDX adoption
- We agreed that for any new format should include an update to the spec with examples for each of the fields (similar to the current RDF and Tag/Value formats)
- We agreed that any new format should have a new example file for the same SPDX document used for the examples attached
- @swinslow will create a branch off of 2.1 we will use to start adding the JSON changes
- An "examples" folder will be added to this repo to contain the SPDX documents

**Comment by kestewart** [comment]
Some concern about the level of documentation in the spec for the alternate formats, and point to examples at a minimum.   However we've got this basically covered so closing this issue off now.
