### ISSUE TITLE
Typo:  2.1 - Fix inconsistent use of spdx: in RDF examples

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#57]
For the RDF examples, some of the SPDX terms use the spdx: prefix, others use no prefix.

This was https://bugs.linuxfoundation.org/show_bug.cgi?id=1369

**Comment by wking** [comment]
This is related to #23, which attempts to tighten our use of the `rdf` and `rdfs` prefixes, and #38, which talks about formalizing our XML schema specification.

**Comment by tsteenbe** [comment]
@kestewart  Can you discuss this with @goneall whether we should do with prefix or without?

**Comment by goneall** [comment]
It is OK to leave off the spdx: if the default namespace prefix for the SPDX document is `http://spdx.org/rdf/terms#`.  It looks like we are inconsistent in the examples on this point.  Although technically OK, we should be consistent.

I suggest we add spdx: in front of all the SPDX terms rather than remove the spdx: from the examples.  This would create a clearer specification.

**Comment by wking** [comment]
> I suggest we add spdx: in front of all the SPDX terms rather than remove the spdx: from the examples. This would create a clearer specification.

Sounds good to me.  Any volunteers?

**Comment by salicodes** [comment]
I will like to volunteer on this, but I need to be clarified on something. Is it like what is on Chapter 3 in the Package Comment section, that instead of reading `RDF: property spdx:comment in class spdx:Package`, it is `RDF: property rdfs:comment in class spdx:Package`. Is that the inconsistency to be dealt with ?

**Comment by goneall** [comment]
Thanks for volunteering. It looks like there's 2 inconsistencies.  The primary one mentioned in this issue is replacing `http://spdx.org/rdf/terms#` with `spdx:`.  You also pointed out another error in the rdf examples.  `spdx:comment` should be replaced by `rdfs:comment`.

**Comment by goneall** [comment]
The PR changes look good.  It just needs to be rebased / merged with more recent changes.

**Comment by iamwillbar** [comment]
PR was merged!
