### ISSUE TITLE
Conditional License Expressions e.g. (IF SOURCE THEN MIT ELSE CC-BY-3.0+)

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#60]
Transferred from https://bugs.linuxfoundation.org/show_bug.cgi?id=1360

**Bill Schineller 2016-05-24 17:51:10 UTC**
From David Wheeler on mailing list http://lists.spdx.org/pipermail/spdx-tech/2016-May/003091.html

In the Linux Foundation CII "best practices" badge effort I'm noticing an interesting problem.  Some projects have *different* license situations for their source code and documentation, but there's no simple way to express that using SPDX License expressions.  Examples of projects where the license isn't easily expressed with SPDX expressions are:
https://bestpractices.coreinfrastructure.org/projects/1
https://bestpractices.coreinfrastructure.org/projects/137

I propose adding a new construct:
"(IF <Condition> THEN <License-Expression> [ELSE <License-Expression>])" to License expressions.
For starters, <Condition> can be:
DOCUMENTATION = True if & only if (iff) documentation
SOURCE = True if & only if (iff) source code

So "Source code under MIT, everything else under CC-BY-3.0 or later" becomes this license expression:
"(IF SOURCE THEN MIT ELSE CC-BY-3.0+)".

If there's no "else" and the condition is false, it'd be interpreted as the empty set of rights ("no rights"), so these would mean the same thing:
"MIT OR (IF DOCUMENTATION THEN CC-BY-3.0+)"
"(IF DOCUMENTATION THEN (MIT OR CC-BY-3.0+) ELSE MIT)"

I imagine Condition could be beefed up to allow AND/OR/NOT, file matching, jurisdiction matching, and comparisons with the current date (for timed releases in the future).  But that's for a later discussion.

--- David A. Wheeler

**Comment by wking** [comment]
On Tue, Jan 02, 2018 at 07:51:19PM +0000, Kate Stewart wrote:
> https://bestpractices.coreinfrastructure.org/projects/137

This project currently has:

  BSD-3-Clause, documentation released under Creative Commons BY-SA
  licenses (both 2.0 and 3.0, depending on when authored).

I'd represent that for the project as:

  BSD-3-Clause AND CC-BY-SA-2.0 AND CC-BY-SA-3.0

although the CC-BY-SA-2.0 allows you to distribute, etc. the content
under the CC-BY-SA-3.0 (and more [1]), so I'd also be comfortable with:

  BSD-3-Clause AND CC-BY-SA-3.0

In both cases, the licensed artifact is *the whole repository* [2]
(although that glosses over the CC0-1.0 license of the included
CC-BY-SA-3.0 text [3], which is the CC's intention based on [4] and
possibly a number of other per-file quirks as well).

The license for a compiled JAR may be just BSD-3-Clause, but I see no
need to represent that information in the *package* license
expression.

If the CII wants to distinguish between package and compiled-artifact
licensing, then I think they want either a full SPDX file with
file-level details or a basic breakdown into the classes that they
feel are important.  E.g. a package license covering everything, a doc
license just for the docs, a program license just for the program(s)
and librar(y|ies), an other license for things that are part of the
package but not docs or programs, ….

The SPDX already has per-file and per-snipped methods for representing
that sort of thing.  I don't think we need the complication of
conditional license expressions.

[1]: https://github.com/spdx/license-list-XML/blob/v3.0/src/CC-BY-SA-2.0.xml#L173-L177
[2]: https://github.com/ESAPI/esapi-java-legacy
[3]: https://github.com/ESAPI/esapi-java-legacy/blob/develop/LICENSE-CONTENT
[4]: https://github.com/spdx/license-list-XML/blob/v3.0/src/CC-BY-SA-4.0.xml#L463-L464

**Comment by pombredanne** [comment]
I think this should not be considered at all. There is however a valid use case that was brought up on list by @david-a-wheeler a while back: being able to state the scope or purpose of an expression. This would be worth digging not this. And there are many ways to think of it and it would likely mean NOT updating the license expression syntax but rather provide a way to express top-level package expressions with some "scoping" of sorts.

**Comment by swinslow** [comment]
I agree with the above comments.

If there's a need for more ways to describe the scope of which files / components a license applies to, I think that should be expressed through use of appropriate fields in an SPDX document. 

If there are concepts that aren't covered through the current fields (e.g. per-file, per-package...) and a conditional is really necessary, then perhaps it could be added into the document spec as a different field or category of information. But it doesn't seem like the license expression syntax is the right place for this.

If this really needed to be part of an SPDX license expression, then I'd say the user should probably instead create a LicenseRef- to represent the specifics of that particular situation.

**Comment by pombredanne** [comment]
@swinslow we think alike there. I cannot see what the value to cram this in the license expression syntax directly.

But a field to specify something like a tag, or classification or facet for a given license may make sense: for instance tagging a file as being a "build script", a "generated file", a "test file", "core code", "documentation", "example code", etc. is useful to help reach a top level licensing or origin conclusion.

For instance,  users may decide that core code is more important than test code or documentation or build scripts and reach their own licensing conclusions at a package-level based on this. The relative importance of each is a choice/policy decision/interpretation and is highly context-specific and depends on the package itself, which part of a given package is used and how it is used by a given user.

So to recap: IMHO adding a field to support this classification and faceting is useful and can then be used for summarization/grouping/clustering of the licensing in a given facet and is super useful to reach a conclusion in a given context. That would not need IMHO any change to the license expressions syntax, especially since this faceting would not be license-related: instead it is file- or directory-specific and it also covers copyright, etc (e.g. any other attributes). For instance, it may be useful to know that core code is from copyright holder XYZ, while test code is from holder ABC.

And related: knowing that in a given context a certain file or package is being used and deployed as opposed to just sit there in an archive and not being "built" or part of a build is also a use flag: for instance, if I use an overall GPL-licensed package where its core code is GPL and some test code and build scripts are-BSD-licensed and these later are not deployed in a given software product/system/application in a given context that's an interesting fact.

**Comment by wking** [comment]
On Wed, Apr 04, 2018 at 08:01:45AM +0000, Philippe Ombredanne wrote:
> So to recap: IMHO adding a field to support this classification and
> faceting…

We already have this in structured information for files [1], and you
can add it in unstructured comments for snippets [2].  I don't think
we need anything new unless you wanted to add the file-type structure
to snippets as well.

[1]: https://github.com/spdx/spdx-spec/blob/df26160783956ed87d78889dd1d4a53022e713eb/chapters/4-file-information.md#43-file-type-
[2]: https://github.com/spdx/spdx-spec/blob/df26160783956ed87d78889dd1d4a53022e713eb/chapters/5-snippet-information.md#59-snippet-comment-

**Comment by iamwillbar** [comment]
I think there is agreement that this can be handled with FILE_TYPE and the license information fields without requiring modification to expressions. Based on that I'm going to close this issue, please reopen if you disagree.
