### ISSUE TITLE
Just a rant re: JSON

### ISSUE THREAD

**Issue by rjb4standards** [spdx/spdx-spec#606]
I'm starting to parse JSON spdx and am finding it a little irritating that the tag names don't match the same case as TV tag names. It sure would be nice to have one consistent spdx data model and tag name taxonomy that is applied consistently across all formats. This would really simplify data searches within an SPDX SBOM.

**Comment by goneall** [comment]
@rjb4standards Having implemented some of the translation tools between the different formats, I understand the frustration.

This was a conscious decision to align with the naming conventions of the serialization format rather than keep them consistent between the formats which we believe will lead to better adoption within the users of that serialization format.

Although I support the decision to have differences in case between the serialization formats, I believe these differences should be formalized and documented in the spec.  Something I think will get addressed in 3.0 with our approach of generating the serialization format specifications.

**Comment by rjb4standards** [comment]
Thanks for your reply Gary. I'll just learn to live with the differences. Fortunately I only need a subset of the total taxonomy for my C-SCRM use case. 
Are there any plans to produce a Vulnerability Disclosure Report format that correlates with an SBOM, i.e. reports vulnerability search results at the component level?

**Comment by goneall** [comment]
> Are there any plans to produce a Vulnerability Disclosure Report format that correlates with an SBOM, i.e. reports vulnerability search results at the component level?

There is a security related profile in the works led by @tsteenbe in the works - contributors welcome :)

**Comment by rjb4standards** [comment]
Thanks, Gary. Much appreciate all your help.

@tsteenbe Thomas, can you point me in the right direction for this work. FYI: I created an open-source Vulnerability Disclosure Report (VDR) in order to satisfy the requirements of the SBOM Bill, H.R. 4611 - am interested in exchanging info. Thanks, Dick Brooks, REA

**Comment by kestewart** [comment]
@goneall - need to update JSON & XML schemas, and automatic drawings.

**Comment by goneall** [comment]
Resolved with PR #716
