### ISSUE TITLE
Contradiction in 6.7, 6.10

### ISSUE THREAD

**Issue by mshawcroft** [spdx/spdx-spec#632]
In Chapter 6.7, the introductory text begins with:

"An optional field for creators.."

The cardinality clause then goes on to state:

"Cardinality | 1..1"

This would appear to be a contradiction.

The same issue appears in chapters: 6.10, 6.11

**Comment by swinslow** [comment]
Good eyes -- this appears to have been an error in the conversion to the format for 2.2.1.

In SPDX 2.2, looking at the PDF version at https://spdx.dev/wp-content/uploads/sites/41/2020/08/SPDX-specification-2-2.pdf, the equivalent fields in sections 2.7, 2.10 and 2.11 say `Cardinality: Optional, one.` It looks like this got incorrectly converted to `Cardinality 1..1` rather than `Cardinality 0..1` in the 2.2.1 version of the spec
