### ISSUE TITLE
Ambiguity for Snippet location in tag-value documents

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-spec#651]
According to [Section 5.2.4 of the 2.2 spec](https://spdx.github.io/spdx-spec/composition-of-an-SPDX-document/#524-snippet-information-section), in tag-value documents:

> If a File contains Snippets, the Snippet Information section shall follow a related File Information section (if it exists in the document).
> Presence of a new file or package section signals the end of the set of snippets associated with the original file, unless an explicit Relationship is used.

I had read this to say that, for tag-value documents, one or more Snippets should be listed immediately after the File that contains them. This would be equivalent to the way that Files contained in a Package are listed immediately after that Package.

However, the [sample 2.2 tag-value document](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXTagExample-v2.2.spdx) doesn't follow this practice: the Snippet `SPDXRef-Snippet` (line 194) does not appear immediately after the File which appears to contain it, `SPDXRef-DoapSource` (line 144). There are several Package sections defined between these two. Is this intentional and correct? 

This might be intended behavior, since the Snippet section contains a `SnippetFromFileSPDXID` field. So I'm not marking this as a "bug" yet.  :)

However, if the intent is not that Snippets need to appear immediately after the corresponding File, then that might be helpful to clarify in [Section 5.2.4](https://spdx.github.io/spdx-spec/composition-of-an-SPDX-document/#524-snippet-information-section) to avoid ambiguity here.

I'm putting this as a 2.2.2 issue, but feel free to push to 2.3 as appropriate.

(Reference: https://github.com/spdx/tools-golang/issues/124 where it seems I've gotten bitten with this, by assuming that Snippets would come immediately after the corresponding Files...)

**Comment by goneall** [comment]
I thought we added the [SnippetFromFileSPDXID](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/chapters/snippet-information.md#92-snippet-from-file-spdx-identifier-field-) to loosen the requirement for the snippet to follow the file.  That being said, the field was added a very long time ago and my memory is not entirely reliable.

Although I don't recall discussing a FileFromPackgeSPDXID field, I'm guessing the files following the package was a convention used in SPDX 1.0 and carried forward for 2.0 for compatibility.  Since Snippets were introduced post 1.0, it didn't have the same compatibility constraint.

The [SPDX Java Tag/Value parser](https://github.com/spdx/spdx-java-tagvalue-store) does not place the snippets immediately after the file, so if we want to impose that restriction, we will need to change the Java code.  I'm not sure how the Python code works, but it should be reviewed as well to see which conventions it follows.

**Comment by ianling** [comment]
The Python library also does not put snippets alongside/within their associated file. The Go library does.

Snippets in tag-value files either need to use `SnippetFromFileSPDXID` or follow the implicit hierarchical ordering of the tag-value format. The example file does the former, which should be supported.

In my opinion, while it is important for these tools to provide a reference implementation for WRITING the various file types with perfect adherence to the spec, these tools should not assume that they will also be READING perfectly valid SPDX files and should instead aim to be useful to developers who might need to read slightly invalid files. There are places where it is safe to make assumptions about what the document creator's intent was (e.g. that a snippet is related to a file using the `SnippetFromFileSPDXID` and not by position within the tag-value file), even if they didn't exactly adhere to the spec.

**Comment by goneall** [comment]
> In my opinion, while it is important for these tools to provide a reference implementation for WRITING the various file types with perfect adherence to the spec, these tools should not assume that they will also be READING perfectly valid SPDX files and should instead aim to be useful to developers who might need to read slightly invalid files.

I also adhere to this philosophy and have attempted to implement them in the Java tools implementation.  In the [SPDX-Java-Library](https://github.com/spdx/spdx-java-library) there is `strict` flag.  If set to true, it will fail for any non-compliant SPDX document.  If it is set to false, it will be more lenient.

I also added an [issue for the Java tag/value parser](https://github.com/spdx/spdx-java-tagvalue-store/issues/21) to allow snippets without the `SnippetFromFileSPDXID`.

Since I don't use the tag/value format myself, I don't plan to implement this feature, but I would support and encourage anyone else who would like to implement it.

**Comment by goneall** [comment]
Since we are not implementing tag/value in the 3.0 release and the current proposed tag/value replacements are significantly different, I'm going to close this issue.

cc: @kestewart
