### ISSUE TITLE
Fix inconsitent camel-casing for FilesAnalyzed

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#72]
Found by @wking: Somewhat unfortunately, the tag/value key (FilesAnalyzed) and RDF/XML
tag (filesAnalyzed) differ in case.  And our internal references seem to use both forms. 

See  also https://github.com/spdx/spdx-spec/pull/69

**Comment by goneall** [comment]
Just confirming the RDF value should be `filesAnalyzed` based on the [RDF schema](https://spdx.org/rdf/terms/dataproperties/filesAnalyzed___1432151612.html) and the [SPDX tools implementation](https://github.com/spdx/tools/blob/69697a44510e38aa7cb58a3024dac2422d7f8275/src/org/spdx/rdfparser/SpdxRdfConstants.java#L161) of the spec.  In reviewing the [tools code](https://github.com/spdx/tools/blob/69697a44510e38aa7cb58a3024dac2422d7f8275/src/org/spdx/tag/SpdxTagValueConstants.properties#L88) for parsing the tag/value it is using `FilesAnalyzed`.  It looks like this is an intentional difference, although I don't recall a discussion.

**Comment by kestewart** [comment]
Based on discussion on tech call,  we have other inconsistencies between RDF and Tag Value in terms of casing,  so concensus is to leave it as is.
