### ISSUE TITLE
Clause 6.5.3 example: unclear how to calculate UUID for DocumentNamespace

### ISSUE THREAD

**Issue by kwijbrans-philips** [spdx/spdx-spec#725]
SPDX 2.2.1 section 6.5 defines the document name space field as http://[CreatorWebsite]/[pathToSpdx]/DocumentName]-[UUID]. If I try to reproduce the UUID in example 6.5.3 using a version 5 UUID from I get to different UUIDs.

Question 1: the example is incomplete - is this deliberate? In addition, it is not clear if it is a version 4 or version 5 UUID. I assume version 4 because none of the version 5 UIDs come close.

Question 2: a version 5 UUID expects a namespace to be defined. Which namespace should be used? My  assumption is that it should be nsURL for URLs and that the payload is "http://[CreatorWebsite]/[pathToSpdx]/DocumentName]". Or is it including the final dash so "http://[CreatorWebsite]/[pathToSpdx]/DocumentName]-"?

**Comment by goneall** [comment]
@kwijbrans-philips I don't think there was any intent to create an incomplete example.  It was done some time ago, but it should be consistent and complete.

Thanks for bringing these issue to light.  Since the example was a best practice and not a requirement, it probably didn't get as much review.

Based on your question 2, I don't think this was clarified or described previously.  From what I can see, either approach will meet the requirements for the document name space.

Did you want to propose a clarification as a pull request?  Although we are just about done with the 2.3 version, there may be time to get the clarification in if we can get a couple reviews in addition to the PR.

**Comment by kwijbrans-philips** [comment]
Yes, will look into this this week.

**Comment by goneall** [comment]
Perhaps I should open this as a separate issue, but I thought I would add a suggestion made by @coderpatros that we use URN's instead of URL's in our example URI's.  From reviewing the [W3C recommendations]([@coderpatros](https://twitter.com/coderpatros)), this looks like a very good suggestion.

I'll definitely bring this up for version 3.0, but since we're looking and clarifying the recommended URI in the 2.X spec, I thought I would mention this suggestion here as well.

**Comment by seabass-labrax** [comment]
I would also like to add that there isn't necessarily a 'right' or 'wrong' way to produce document namespaces - extra guidance is always good of course :smiley:

**Comment by kestewart** [comment]
We don't have a volunteer to update this, so moving this to 3.0

**Comment by goneall** [comment]
This has been removed in the 3.0 spec - so I'm going to go ahead and close this issue since we don't have any volunteers to implement a PR
