### ISSUE TITLE
Consider inclusion of SHA1-DC in SPDX 3.0

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-spec#737]
From meeting, there is still too much ambiguity around the algorithm to include in 2.3.

see: https://github.com/spdx/spdx-spec/pull/734 for background.

**Comment by seabass-labrax** [comment]
The discussion we had during the 2022-07-05 SPDX Tech Team meeting centered mainly on:

- whether or not SHA1-DC was in fact a different hash algorithm from SHA1
- if *not* distinct in substance from SHA1, whether its use in SPDX would signify an assertion that collision detection was performed

No conclusion was reached, due to the desire to allocate time to more immediate topics for the release of SPDX 2.3.

@kestewart, is this something that you (or David Wheeler) are still interested in pursuing for SPDX 3.0?

**Comment by kestewart** [comment]
Closing this for now, if the topic comes up in future a new issue should be created, better documenting where it is found in the wild, and justifying why it should be treated diffently from SHA1.
