### ISSUE TITLE
Ontology issues (collected)

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-spec#757]
While generating the diagrams and documentation for the ontology, I went at it with a very fine comb...

@goneall these are issues that I found. Most of them are minor, but it wouldn't hurt to have them fixed.

I assume you will work on Protege, so I won't volunteer to provide textual patches to the `.xml` file. For this reason, I also do not provide line numbers on each one; let me know if you need them.

1. `primaryPackagePurpose` has no range (should be `Purpose`)
2. `referenceCategory` has no range (should be `ReferenceCategory`)
3. `externalDocumentRef` has no range (should be `ExternalDocumentRef`)
4. `order` has no domain (should be `CrossRef`)
5. `hasExtractedLicensingInfo` has two domains, but `ExtractedLicensingInfo` should be its range
6. `range` (in `Snippet`) is shown as having range (ha!) both `CompoundPointer` and `StartEndPointer` at different places
7. in `SpdxDocument`, there are restrictions that `dataLicense` can be `AnyLicenseInfo` but also that it has to be `http://spdx.org/licenses/CC0-1.0`
8. there is a reference to `http://www.w3.org/2000/01/rdf-schema#member` which is confusing, given that we have our own `http://spdx.org/rdf/terms#member`
9. `licenseInfoFromFiles` in `SpdxItem`(and corresponding sublasses in packages, files, snippets) seem to be `SimpleLicenseInfo` (or NOASSERTION or NONE). Why aren't license expressions allowed?
10. `License` has `licenseText`, `standardLicenseTemplate`, `standardLicenseHeader`, and `standardLicenseHeaderTemplate`.  `ListedLicense` has `licenseTextHtml` `standardLicenseHeaderHtml`.  However, `standardLicenseHeaderTemplate` has domain `ListedLicense` instead of `License`.

Sorry about all this!

**Comment by goneall** [comment]
Thanks @zvr - you really did go through a thorough review.

I'll take a look at these and see if I can get some fixes in today or tomorrow.

**Comment by goneall** [comment]
I think the range in snippets (number 6 above) is OK since StartEndPointer is subclass of CompoundPointer and the more specific restriction is a subclass of the Snippet class.  However, I'm not completely sure.  We could just remove the range on the range property or change the Snippet range.  @zvr - let me know your thoughts on this.

**Comment by goneall** [comment]
The 2 restrictions on the dataLicense (number 7 above) was by design.  Since the specific datalicense if a specific instance of AnyLicenseInfo, I don't think there is a contradiction.  The reason I put both of these as restrictions on dataLicense is that there has always been controversy about having only one choice and if we ever decided to remove the single license restriction, we could just remove the CC0 restriction and leave the AnyLicenseInfo.

**Comment by zvr** [comment]
6. `range`

I'd vote for using only `StartEndPointer` everywhere, i.e. change the range of `http://spdx.org/rdf/terms#range`

9. `licenseInfoFromFiles`

I believe this is a bug in the spec; I'll open a new issue for it to fix the description.
I assume in the ontology the fix would be to change the restrictions from `SimpleLicenseInfo | NOASSERTION | NONE` to `AnyLicenseInfo | NOASSERTION | NONE`, right?

**Comment by goneall** [comment]
I just pushed a new commit to change the range of `http://spdx.org/rdf/terms#range` which should fix number 6 above in PR #759 

For number 9, I tend to agree we should fix the spec and ontology + the model diagram to allow AnyLicenseInfo, but since it is a more substantial change I would suggest fixing all of these inconsistencies at the same time.

**Comment by goneall** [comment]
@zvr I think this is resolved enough for version 2.3 - if you agree, please close the issue.

**Comment by zvr** [comment]
Yes, the only remaining is point 9 above, which we'll follow up in #760.
