### ISSUE TITLE
Should licenses found in code be license expressions ?

### ISSUE THREAD

**Issue by zvr** [spdx/spdx-spec#760]
We have many ways of referring to licenses found in source code (using the tag-value names of the properties):
- at Package level, there is [PackageLicenseInfoFromFiles](https://spdx.github.io/spdx-spec/v2.3/package-information/#714-all-licenses-information-from-files-field)
- at File level, there is [LicenseInfoInFile](https://spdx.github.io/spdx-spec/v2.3/file-information/#86-license-information-in-file-field)
- at Snippet level, there is [LicenseInfoInSnippet](https://spdx.github.io/spdx-spec/v2.3/snippet-information/#96-license-information-in-snippet-field)

All these are defined to be a **single** license (or `NOASSERTION` or `NONE`). I believe that this is a mistake, and they should all be _License Expressions_.

Actually, it's even worse than that:
- all three descriptions talk about single license
- the metadata in the File and Snippet case say it's an expression or a single license (which makes no sense)

I propose we homogenize all three sections with the same text and metadata, clearly saying it's a License Expression (as in Annex D) or NOASSERION or NONE.

**Comment by zvr** [comment]
Forgot to add: @goneall did some historical research and it seems we have this since at least 2.0.

**Comment by swinslow** [comment]
Hi @zvr -- I started a longer reply on this and then lost it, ugh.

I believe this is _not_ an error, rather a design decision that was intentionally made with the original intention for these fields. It pre-dates my involvement with SPDX which is why I'm not speaking more affirmatively on it, but I believe some of this was discussed when we were considering the fields for the license profile for 3.0 last year.

I would say:
1) this should not be changed for 2.x, given that it would be breaking changes
2) for 3.0, I believe we were making changes to these fields anyway to capture the use cases that were discussed, so I think this will be addressed for _some_ of these

**Comment by zvr** [comment]
OK, @swinslow , care to explain it a little more?

You mean that anything in a file or package can _not_ be found to be, e,g, under `GPL-2.0-only OR BSD-3-Clause` but it should have a single license?
Because this is what the description says.

As I've written, of course, the "metadata" table format for File and Snippet has the "License Expression" added. In this case, should we fix the metadata and remove the License Expression? Because now there is conflicting information.

**Comment by swinslow** [comment]
@zvr Apologies for the short response earlier, I was traveling all weekend and tried to reply quickly.

Here's my understanding of the meanings and intended uses of these fields. This is purely guessing because all of these fields pre-date my involvement with SPDX (@jlovejoy @pmadick @goneall @kestewart feel free to weigh in if you have more background on these)

* I believe the original purpose of each of these fields was to have a list / array of _single license IDs_ -- not license expressions. If there are multiple licenses found, then at least in the tag-value world you list successive `LicenseInfoInFile: XYZ` single license entries.
  * So, for instance with LicenseInfoInFile, the idea is to have a list of licenses just to express the literal fact of "I found a reference to this license in this file," while intentionally not saying anything about how they are combined into an expression. Same for the Package and Snippet variants.
  * Personally, I have no use for this use case, so please don't ask me to argue in favor of these fields. I'm just clarifying why I believe it was originally added.  :)
* In [SPDX 2.0, section 4.6.4](https://spdx.dev/wp-content/uploads/sites/41/2017/12/spdx-2.0.pdf), the data format for LicenseInfoInFile was originally a single license ID (including LicenseRef's) which matches the text description in 4.6.1.
* In [SPDX 2.1, section 4.6.4](https://spdx.dev/spdx-specification-21-web-version/#h.111kx3o), it looks like the data format was changed to permit license expressions instead -- although the text of 4.6.1 still refers to single licenses. This may have been an error, or may have been for a reason that I'm not understanding at the moment (again, this all pre-dates me). It looks like Git wasn't being used yet for SPDX 2.1 development so I don't know the history on this.
* For `LicenseInfoInSnippet`, it looks like snippets didn't exist in 2.0 and when they were added in 2.1 it included the same issue as `LicenseInfoInFile`, where the text describes a series of single licenses but the data format mentions license expressions.
* For `PackageLicenseInfoFromFiles` the current text description and data format appear to be in sync, both referring to a list of single licenses.

As far as how to resolve this for 2.3:
* For `PackageLicenseInfoFromFiles` I wouldn't change anything, since it appears they're still correctly describing the intent here.
* For `LicenseInfoInFile` and `LicenseInfoInSnippet`, having looked at this more closely, it does look like there's a conflict that will need to be resolved one way or the other: either changing the data formats to fit the text description of a list of single licenses, or changing the text to refer to a list of license expressions.
* I don't have a personal preference which option to take. I would lean _slightly_ towards switching the text to fit the data format, so that it will be a list of license expressions.
  * I think that is the _least incompatible_ option with 2.2 and 2.1, because any documents that were following the "list of single licenses" approach would still be valid if it switches to "list of license expressions".
  * Whereas if it goes the other direction, then any old documents following the "list of license expressions" would become incompatible if it reverts to "list of single licenses".

For 3.0, I believe the intention is potentially to preserve `PackageLicenseInfoFromFiles` as a list of single licenses, but to replace `LicenseInfoInFile` and `LicenseInfoInSnippet` with something more like `DeclaredLicense`. So this issue will likely go away, but I understand (and appreciate better now!) the desire to resolve it for 2.3.

**Comment by zvr** [comment]
Thanks for the expanded input, @swinslow.

The issue I'm seeing is, that if we do not allow License Expressions (any more?), what happens when I have a snippet/file with something like `GPL-2.0-only OR BSD-3-Clause` or even `Apache-2.0 WITH-LLVM-exception`? How do I record this on the upper level (File, Package)? Do I have to break the expression into single licenses?

To phrase it differently: I am not concerned with these entries _combining_ licenses found into expressions; I wonder how they should record license expressions _already present_ in the code in question.

**Comment by swinslow** [comment]
Yup, I agree this is a potential consideration / concern.

I believe the original intent of the `LicenseInfoIn___` fields was simply to say "I found a reference to license XYZ in the Package/File/Snippet". The `LicenseConcluded` fields are then meant to be the place where the licenses are actually combined into expressions using `AND`s and `OR`s.

For exceptions, looking at the SPDX 2.0 spec I think it would have worked the same way, putting the short identifier from the exception list into the `LicenseInfoIn____` field and then actually combining it with the license via a `WITH` into a license expression for the `LicenseConcluded` field.

Just to be clear, I don't have a particular preference for how to resolve this, though as mentioned above I lean towards changing the text descriptions of `LicenseInfoInFile` and `LicenseInfoInSnippet` to describe license expressions, to align with the data formats defined for those fields starting in SPDX 2.1.

**Comment by goneall** [comment]
I don't recall the discussion on the changes to this field in 2.1, so I can't offer any historical perspective.

In terms of what we what we should do going forward, I think we should allow license expressions for the following reasons:
- The current spec is ambiguous and different readers may have implemented different parsers - we need to choose one approach (single license ID's or license expressions)
- License expressions are backwards compatible with single license IDs whereas going from license expressions to single license ID's are not backwards compatible
- We allow license expressions text files per [Annex E](https://github.com/spdx/spdx-spec/blob/development/v2.3/chapters/using-SPDX-short-identifiers-in-source-files.md#e2-format-for-spdx-license-identifier-). I think we should have the LicenseInfoIn... be consistent this Annex.

**Comment by goneall** [comment]
I created a draft PR #764 to change update the RDF ontology if the above recommendation is accepted.

**Comment by goneall** [comment]
Resolved with PR #771
