### ISSUE TITLE
SPDX Spec URL points to 2.2.2 spec - should be 2.3

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-spec#803]
https://spdx.github.io/spdx-spec/ points to 2.2.2 instead of 2.3

@iamwillbar @tsteenbe Could you both take a look at this and see if it can be fixed?  We have a number of website which use this URL for the current version.

**Comment by nicoweidner** [comment]
To add to this, since we also noticed recently: In the URL Gary posted, there is no version selection dropdown in the top left. When navigating to a version-specific URL such as https://spdx.github.io/spdx-spec/v2.3/, the dropdown appears (see screenshot).
I think having the dropdown on the "main" page would be good!
![Screenshot from 2022-10-31 10-42-56](https://user-images.githubusercontent.com/66428403/198978808-f69c13f1-227b-4726-a2ec-a104bb7f47b2.png)

**Comment by maxhbr** [comment]
The publish step only runs, if both `build_current` and `build_v2-draft` were executed
https://github.com/spdx/spdx-spec/blob/4021a7ae502352cd79bae2979859f28072fc402f/.github/workflows/publish.yml#L46-L49

But
* `build_current` only runs on `'refs/heads/master'` and
* `build_v2-draft` only runs on `'refs/heads/development/v2.3'`

so they never run both.

As a result, the publish is never executed.

**Comment by goneall** [comment]
Thanks @maxhbr for the quick analysis and PR.

You'll find some related PR's where we've tried to fix similar issues - perhaps one of those PR's caused this issue?

**Comment by goneall** [comment]
From a quick check - it looks like this has been resolved
