### ISSUE TITLE
JSON schema uses licenseInfoInSnippets (plural) instead of licenseInfoInSnippet

### ISSUE THREAD

**Issue by nicoweidner** [spdx/spdx-spec#804]
I assume this is a typo: [In the json schema](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/schemas/spdx-schema.json#L639), the property name is in plural, whereas it's singular [in the spec](https://spdx.github.io/spdx-spec/v2.3/snippet-information/#96-license-information-in-snippet-field) (rdf and tagValue examples).

The singular version makes more sense, imho, since it describes the license info contained in a single snippet.

I'm happy to put up a small PR to fix this if everyone agrees it should be fixed (there may be "breaking change" considerations involved...)

**Comment by goneall** [comment]
@nicoweidner The schema is actually generated from the [OWL Ontology](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/ontology/spdx-ontology.owl.ttl) using the [Schema converter utility](https://github.com/spdx/tools-java/blob/master/src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java).

The utility converts any property with a cardinality allowing more than 1 to plural.

In this particular case, it should be `licenseInfosInSnippet` rather than `licenseInfoInSnippets` - however, the utility isn't smart enough to do that type of conversion.

One fix would be to special case the `licenseInfoInSnippet` property in the generator code.  A bit hacky, but probably an OK approach.

In terms of a breaking change, it would break existing JSON files - so I'm a bit reluctant to make the change even though the change does make sense.

**Comment by nicoweidner** [comment]
@goneall Thanks for the explanation (and I agree the correct plural version is hard for a tool to determine). I agree it's probably not worth it to break existing files for this change. 3.0 can fix it...

**Comment by goneall** [comment]
Setting a 3.0 Milestone and opening a parallel issue for the schema generator utility: https://github.com/spdx/tools-java/issues/92

**Comment by seabass-labrax** [comment]
For 3.0, we might not have `licenseInfoInSnippet`, as licensing information may be abstracted to artefacts in general (files, packages, snippets etc.). However, the method of representing licensing information in 3.0 is still the subject of active discussion within the Legal and Tech teams.

**Comment by goneall** [comment]
In 3.0 we decided to only use the singular form (even if the cardinality is more than one).

Closing this issue.
