### ISSUE TITLE
How to deal with deprecated FileDependencies?

### ISSUE THREAD

**Issue by meretp** [spdx/spdx-spec#827]
The [spec](https://spdx.github.io/spdx-spec/v2.3/file-information/#816-file-dependencies-field-deprecated) says that the field FileDependencies is deprecated in favor of using relationships. for the refactored version of the python-tools we try to replace deprecated field wiith the favoured ones, but as there are many dependency-relationships, I was wondering how to convert a `FileDependency` to a relationship. 
Consider the following example:
```
File
SPDXID: SPDXRef-File
FileDependency: a-dependency
```
Would the resulting relationship be `SPDXRef-File DEPENDS_ON a-dependency`? Or as the description from the spec says "the file is a derivative of and/or depends on for the build" would the relationship be `SPDXRef-File BUILD_DEPENDENCY_OF a-dependency`?

**Comment by goneall** [comment]
Good question.

I just checked the Java tools and the SPDX Spreadsheet converts the `FileDependency` to the `DEPENDS_ON` relationship.

Since `DEPENDS_ON` is more general, I believe it would be the safer choice - but I could easily be convinced `BUILD_DEPENDENCY_OF` is a better choice.

Note that no conversion is currently done for the tag/value or RDF store - they continue to use the deprecated property.

**Comment by meretp** [comment]
I see, thanks Gary! I would agree that the more general choice is safer, so I think we will also use `DEPENDS_ON` in the python tools.

**Comment by goneall** [comment]
Closing this as resolved -
