### ISSUE TITLE
Mandating CC0 on SPDX documents considered harmful.

### ISSUE THREAD

**Issue by MarkAtwood** [spdx/spdx-spec#850]
I would like to reopen the topic of https://github.com/spdx/spdx-spec/issues/159 and https://wiki.spdx.org/images/SPDX-TR-2014-1.v1.1.pdf

Amazon has severe reservations about being required to tag the SBOMs of our internal services and delivered products as CC0, even if there is also an NDA in place.

We especially don't want to have "you put a CC0 on it" when someone else publishes something that was provided to them by someone breaking their NDA, and do not want to have to literally litigate that topic. 

The other SBOM standards do not require a CC0 or other license tag.

**Comment by Artoria2e5** [comment]
> when someone else publishes something that was provided to them by someone breaking their NDA

Copyright is not for keeping secrets. Federal employee work is always public domain (~CC0). See how much trouble the Air National Guard Kid got into?

Claiming copyright on something as mechanical as an SBOM is a bad idea. Even if you claimed it, you need to somehow argue that you satisfy the threshold of originality, so you end up literally litigating another way.

**Comment by ddillard** [comment]
Copyright isn't for keeping secrets, but it is necessary in order to maintain confidentiality.  As noted on the [Creative Commons website](https://wiki.creativecommons.org/wiki/CC0_FAQ#:~:text=CC0%20is%20legally%20operative%20in,related%20or%20neighboring%20rights%20worldwide.) (emphasis is mine) "CC0 is legally operative in the sense that when it is applied, it changes the copyright status of the work, **effectively relinquishing all copyright and related or neighboring rights worldwide.**"  If I don't own it then I can't license it and licensing can be used for maintaining confidentiality.

I agree with Mark, this should be changed.

**Comment by goneall** [comment]
This has been resolved in 3.0 with the implementation of the change proposal to remove the restriction of CC0
