### ISSUE TITLE
Spec not corresponding to the model image & specification lacks descriptions about necessity of properties

### ISSUE THREAD

**Issue by gmscofield** [spdx/spdx-spec#980]
SPDX specification( https://spdx.github.io/spdx-spec/v3.0/ ) doesn't seem to correspond to the model image in https://github.com/spdx/spdx-3-model/ . 
For example, AIPackage class in AI profile is subclass of Package class in Software profile. There is no other descriptions in the specification, so I thought that all properties in Package class are usable in AIPackage class(or AI profile). However, after I saw the model AI image( https://github.com/spdx/spdx-3-model/blob/main/model%20AI.png ) in spdx-3-model repository, there are only 3 properties of Package class included in AIPackage class, not all 5. I don't know if there were something wrong with the model image or the specification lacked some descriptions about the necessary properties.

**Comment by bact** [comment]
The reason that those Package properties are included again in AIPackage is because they have different cardinality from Package.

Please refer to "External properties restrictions" section in
https://github.com/spdx/spdx-3-model/blob/main/model/AI/Classes/AIPackage.md

Note that the spec doc at https://spdx.github.io/spdx-spec/v3.0/ currently not showing the "External properties restrictions". It's a known bug to be fixed. (soon, see: https://github.com/spdx/spec-parser/issues/125)

**Comment by kestewart** [comment]
Please review 3.0.1 (https://spdx.github.io/spdx-spec/v3.0.1-draft/) and let us know if this still needs to be improved.

**Comment by goneall** [comment]
It looks like this is resolved - so closing.  @gmscofield - if you disagree, please (re) open an issue.
